/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yip_yipjnidemo_JniText */

#ifndef _Included_com_yip_yipjnidemo_JniText
#define _Included_com_yip_yipjnidemo_JniText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yip_yipjnidemo_JniText
 * Method:    getCLangString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yip_yipjnidemo_JniText_getCLangString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
